// scripts/seed.ts
import { initializeApp } from 'firebase/app';
import { getFirestore, collection, doc, writeBatch } from 'firebase/firestore';

const firebaseConfig = {
  apiKey: 'AIzaSyDWD_-8YS0ov4ufsb1qOCwn2xHJRQajlzk',
  authDomain: 'mudo-project-9666a.firebaseapp.com',
  projectId: 'mudo-project-9666a',
  storageBucket: 'mudo-project-9666a.firebasestorage.app',
  messagingSenderId: '953204120724',
  appId: '1:953204120724:web:439065152574d205946881',
  measurementId: 'G-2ZC9SXZ9NC',
};

// Firebase 초기화
const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

// 더미 데이터
const dummyData = [
  {
    title: '약간 모자라지만 착한 친구야',
    description: '멍청이를 우리말로 순화해서 말하는 장면',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-002.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-002.png?raw=true',
    cast: ['정준하'],
    tags: ['웃김', '놀림', '디스'],
    keyword: 'ㅇㄱㅁㅈㄹㅈㅁㅊㅎㅊㄱㅇ',
    episodeNum: 270,
    episodeDate: '2011년 10월 8일',
    episodeName: '무한상사 특집',
  },
  {
    title: '정신차려 이 각박한 세상속에서',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-003.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-003.png?raw=true',
    cast: ['하하'],
    tags: ['웃김', '경고', '설득', '자막짤'],
    keyword: 'ㅈㅅㅊㄹㅇㄱㅂㅎㅅㅅㅅㅇㅅ',
    episodeNum: 333,
    episodeDate: '2013년 6월 8일',
    episodeName: '행쇼',
  },
  {
    title: '지금 지쳤나요?',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-004.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-004.png?raw=true',
    cast: ['홍진경'],
    tags: ['웃김', '힘듦', '피곤', '자막짤'],
    keyword: 'ㅈㄱㅈㅊㄴㅇ?',
    episodeNum: 422,
    episodeDate: '2015년 4월 4일',
    episodeName: '식스맨 특집',
  },
  {
    title: '사랑아, 보영해',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-005.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-005.png?raw=true',
    cast: ['정형돈', '일반인'],
    tags: ['웃김', '사랑', '자막짤'],
    keyword: 'ㅅㄹㅇㅂㅇㅎ',
    episodeNum: 280,
    episodeDate: '2011년 12월 17일',
    episodeName: '무한택배',
  },
  {
    title: '형이 왜 거기서 나와?',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-006.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-006.png?raw=true',
    cast: ['정형돈'],
    tags: ['웃김', '왜 거기서 나와', '당황', '자막짤'],
    keyword: 'ㅎㅇㅇㄱㄱㅅㄴㅇ?',
    episodeNum: 408,
    episodeDate: '2014년 12월 13일',
    episodeName: '유혹의 거인',
  },
  {
    title: '출바알',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-007.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-007.png?raw=true',
    cast: ['박명수'],
    tags: ['출발', '여행', '자막짤'],
    keyword: 'ㅊㅂㅇ',
    episodeNum: 266,
    episodeDate: '2011년 9월 10일',
    episodeName: '한가위 선물 특집',
  },
  {
    title: '정자룡이 간다 간다 뿅 간다',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-008.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-008.png?raw=true',
    cast: ['박명수', '정준하', '길'],
    tags: ['웃김', '가자', '자막짤'],
    keyword: 'ㅈㅈㄹㅇㄱㄷㄱㄷㅃㄱㄷ',
    episodeNum: 217,
    episodeDate: '2010년 09월 25일',
    episodeName: '다 같이 돌자 서울 한바퀴~ 빙고 특집',
  },
  {
    title: '늦었다고 생각할 때가 진짜 너무 늦었다',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-009.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-009.png?raw=true',
    cast: ['박명수'],
    tags: ['충고', '늦음', '공부', '지각'],
    keyword: 'ㄴㅇㄷㄱㅅㄱㅎㄸㄱㅈㅉㄴㅁㄴㅇㄷ',
    episodeNum: 164,
    episodeDate: '2009년 8월 1일',
    episodeName: '소원을 말해봐 특집',
  },
  {
    title: '꿈은 없고요 그냥 놀고 싶습니다',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-010.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-010.png?raw=true',
    cast: ['무도멤버'],
    tags: ['지침', '공부', '놀자', '쉬자'],
    keyword: 'ㄲㅇㅇㄱㅇㄱㄴㄴㄱㅅㅅㄴㄷ',
    episodeNum: 343,
    episodeDate: '2013년 8월 17일',
    episodeName: '무도를 부탁해',
  },
  {
    title: '나 드러워서 못하겠네',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-011.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-011.png?raw=true',
    cast: ['박명수', '정준하'],
    tags: ['투덜', '불만', '중얼중얼'],
    keyword: 'ㄴㄷㄹㅇㅅㅁㅎㄱㄴ',
    episodeNum: 410,
    episodeDate: '2014년 12월 27일',
    episodeName: '토토가',
  },
  {
    title: '말 좀 제대로 해라',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-012.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-012.png?raw=true',
    cast: ['하하', '정형돈'],
    tags: ['호통', '핀잔', '뭐라는 거야'],
    keyword: 'ㅁㅈㅈㄷㄹㅎㄹ',
    episodeNum: 292,
    episodeDate: '2012년 8월 25일',
    episodeName: '니가 가라 하와이',
  },
  {
    title: '일본 형돈이',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-013.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-013.png?raw=true',
    cast: ['정준하'],
    tags: ['닮은꼴', '정형돈', '일본'],
    keyword: 'ㅇㅂㅎㄷㅇ',
    episodeNum: 237,
    episodeDate: '2011년 2월 19일',
    episodeName: '오호츠크해 특집',
  },
  {
    title: '유식해 보이는 무식한 답변',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-014.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-014.png?raw=true',
    cast: ['하하'],
    tags: ['신기', '무식', '민망'],
    keyword: 'ㅇㅅㅎㅂㅇㄴㅁㅅㅎㄷㅂ',
    episodeNum: 238,
    episodeDate: '2011년 2월 26일',
    episodeName: '오호츠크해 특집',
  },
  {
    title: '아버지 나를 낳으시고 바지적삼 다적시셨네',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-015.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-015.png?raw=true',
    cast: ['정준하', '박명수', '유재석'],
    tags: ['아나바다', '사행시'],
    keyword: 'ㅇㅂㅈㄴㄹㄴㅇㅅㄱㅂㅈㅈㅅㄷㅈㅅㅅㄴ',
    episodeNum: 298,
    episodeDate: '2012년 10월 6일',
    episodeName: '추석특집 무한상사',
  },
  {
    title: '뱀이야 xx야',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-016.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-016.png?raw=true',
    cast: ['길', '정형돈'],
    tags: ['뱀', '욕', '나쁜말', '다급'],
    keyword: 'ㅂㅇㅇXXㅇ',
    episodeNum: 344,
    episodeDate: '2013년 8월 24일',
    episodeName: '무도를 부탁해',
  },
  {
    title: '점 오',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-017.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-017.png?raw=true',
    cast: ['박명수'],
    tags: ['1.5', '쩜오', '나지막이', '뒷모습'],
    keyword: 'ㅈㅇ',
    episodeNum: 194,
    episodeDate: '2010년 2월 27일',
    episodeName: '죄와 길',
  },
  {
    title: '한머리 두냄새',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-018.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-018.png?raw=true',
    cast: ['유재석', '정형돈', '박명수', '하하', '정준하', '길'],
    tags: ['미스터리', '냄새', '머리', '두피'],
    keyword: 'ㅎㅁㄹㄷㄴㅅ',
    episodeNum: 204,
    episodeDate: '2010년 6월 26일',
    episodeName: '자리분양 특집',
  },
  {
    title: '간염에 걸렸을때 일어나지 못했더라면',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-019.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-019.png?raw=true',
    cast: ['박명수'],
    tags: ['IF', '만약에', '독설', '간염'],
    keyword: 'ㄱㅇㅇㄱㄹㅇㄸㅇㅇㄴㅈㅁㅎㄷㄹㅁ',
    episodeNum: 363,
    episodeDate: '2014년 1월 4일',
    episodeName: 'IF 만약에',
  },
  {
    title: '이제는 더 이상 물러날 곳이 없다',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-020.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-020.png?raw=true',
    cast: ['정준하'],
    tags: ['응원가', '수능', '없없무', '춤', '댄스'],
    keyword: 'ㅇㅈㄴㄷㅇㅅㅁㄹㄴㄱㅇㅇㄷ',
    episodeNum: 274,
    episodeDate: '2011년 11월 5일',
    episodeName: '수학능력평가 특집',
  },
  {
    title: '형보다 잘할걸?',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-021.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-021.png?raw=true',
    cast: ['길'],
    tags: ['일침', '아마도', '결혼발표'],
    keyword: 'ㅎㅂㄷㅈㅎㄱ?',
    episodeNum: 292,
    episodeDate: '2012년 8월 25일',
    episodeName: '무한뉴스',
  },
  {
    title: '아유... 하기 싫어...',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-022.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-022.png?raw=true',
    cast: ['박명수'],
    tags: ['마음의 소리', '회사원', '하기 싫어', '속마음', '한숨'],
    keyword: 'ㅇㅇㅎㄱㅅㅇ',
    episodeNum: 285,
    episodeDate: '2012년 1월 21일',
    episodeName: '무한상사',
  },
  {
    title: '참재밌다',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-023.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-023.png?raw=true',
    cast: ['박명수'],
    tags: ['재미', '웃음', '놀이'],
    keyword: 'ㅊㅈㅁㄷ',
    episodeNum: 278,
    episodeDate: '2011년 12월 3일',
    episodeName: '명수는 12살',
  },
  {
    title: '자 이게 클릭이야',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-024.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-024.png?raw=true',
    cast: ['노홍철', '하하'],
    tags: ['클릭', '모자람', '충고', '첫걸음'],
    keyword: 'ㅈㅇㄱㅋㄹㅇㅇ',
    episodeNum: 270,
    episodeDate: '2011년 10월 8일',
    episodeName: '무한상사',
  },
  {
    title: '형이 모자라다고 말 함부로 하냐',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-025.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-025.png?raw=true',
    cast: ['박명수'],
    tags: ['모자람', '일침', '충고', '나무람'],
    keyword: 'ㅎㅇㅁㅈㄹㄷㄱㅁㅎㅂㄹㅎㄴ',
    episodeNum: 38,
    episodeDate: '2007년 1월 27일',
    episodeName: '7080 복고 특집',
  },
  {
    title: '그래도 하시겠습니까?',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-026.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-026.png?raw=true',
    cast: ['일반인'],
    tags: ['선서', '???', '증인', '법정', '위증'],
    keyword: 'ㄱㄹㄷㅎㅅㄱㅅㄴㄲ',
    episodeNum: 194,
    episodeDate: '2010년 2월 27일',
    episodeName: '죄와 길',
  },
  {
    title: '반갑다 x세대 여러분',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-027.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-027.png?raw=true',
    cast: ['박명수'],
    tags: ['복학생', 'X세대', '인사'],
    keyword: 'ㅂㄱㄷxㅅㄷㅇㄹㅂ',
    episodeNum: 289,
    episodeDate: '2012년 8월 4일',
    episodeName: '개그학개론',
  },
  {
    title: '무야호',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-028.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-028.png?raw=true',
    cast: ['일반인'],
    tags: ['무야호', '함성', '야호', '신남'],
    keyword: 'ㅁㅇㅎ',
    episodeNum: 195,
    episodeDate: '2010년 3월 6일',
    episodeName: '오 마이 텐트 특집',
  },
  {
    title: '더덩실 더덩실',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-029.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-029.png?raw=true',
    cast: ['유재석', '박명수'],
    tags: ['어깨춤', '더덩실', '신나', '즐겨'],
    keyword: 'ㄷㄷㅅㄷㄷㅅ',
    episodeNum: 175,
    episodeDate: '2009년 10월 17일',
    episodeName: '벼농사 특집',
  },
  {
    title: '지난번만 못하네요 어머님',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-030.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-030.png?raw=true',
    cast: ['박명수'],
    tags: ['어머님', '반찬', '아쉬움', '영상편지'],
    keyword: 'ㅈㄴㅂㅁㅁㅎㄴㅇㅇㅁㄴ',
    episodeNum: 132,
    episodeDate: '2008년 11월 29일',
    episodeName: '무한도전, 에어로빅에 도전하다',
  },
  {
    title: '법보다 가까운 주먹',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-031.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-031.png?raw=true',
    cast: ['박명수', '유재석', '정준하', '정형돈'],
    tags: ['법정', '깽판', '난동', '주먹'],
    keyword: 'ㅂㅂㄷㄱㄲㅇㅈㅁ',
    episodeNum: 193,
    episodeDate: '2010년 2월 20일',
    episodeName: '죄와 길',
  },
  {
    title: '친구들아 고맙다',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-032.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-032.png?raw=true',
    cast: ['박명수'],
    tags: ['감사', '고마움', '인자한 미소', '친구', '우정'],
    keyword: 'ㅊㄱㄷㅇㄱㅁㄷ',
    episodeNum: 278,
    episodeDate: '2011년 12월 3일',
    episodeName: '명수는 12살',
  },
  {
    title: '한번 고소당해야 정신 차리시겠습니까',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-033.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-033.png?raw=true',
    cast: ['박명수'],
    tags: ['고소', '으름장', '윽박', '경고'],
    keyword: 'ㅎㅂㄱㅅㄷㅎㅇㅈㅅㅊㄹㅅㄱㅅㄴㄲ',
    episodeNum: 279,
    episodeDate: '2011년 12월 10일',
    episodeName: '명수는 12살',
  },
  {
    title: '홍철이 없는 홍철팀 탄생',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-034.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-034.png?raw=true',
    cast: ['길', '유재석', '정준하', '하하', '박명수'],
    tags: ['노홍철', '팀', '팀명'],
    keyword: 'ㅎㅊㅇㅇㄴㅎㅊㅌㅌㅅ',
    episodeNum: 217,
    episodeDate: '2010년 9월 25일',
    episodeName: '다 같이 돌자 서울 한바퀴~ 빙고 특집',
  },
  {
    title: '족발 당수 워어어어',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-035.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-035.png?raw=true',
    cast: ['정형돈'],
    tags: ['족발', '당수', '안전'],
    keyword: 'ㅈㅂㄷㅅㅇㅇㅇㅇ',
    episodeNum: 163,
    episodeDate: '2009년 7월 25일',
    episodeName: 'SOS 해양구조대 특집',
  },
  {
    title: '쯔왑 쯔왑',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-036.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-036.png?raw=true',
    cast: ['황광희'],
    tags: ['쯔왑쯔왑', '간식', '식사', '맛도리'],
    keyword: 'ㅉㅇㅉㅇ',
    episodeNum: 461,
    episodeDate: '2016년 1월 2일',
    episodeName: '무도 공개수배',
  },
  {
    title: '너 왜 반말?',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-037.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-037.png?raw=true',
    cast: ['유병재'],
    tags: ['의문', '일침', '반말'],
    keyword: 'ㄴㅇㅂㅁ?',
    episodeNum: 421,
    episodeDate: '2015년 3월 28일',
    episodeName: '식스맨',
  },
  {
    title: '참... 좋다',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-038.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-038.png?raw=true',
    cast: ['정준하'],
    tags: ['바보', '미소'],
    keyword: 'ㅊ...ㅈㄷ',
    episodeNum: 281,
    episodeDate: '2011년 12월 24일',
    episodeName: '무한택배',
  },
  {
    title: '성희롱 당한 NO홍철',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-039.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-039.png?raw=true',
    cast: ['노홍철'],
    tags: ['성희롱', '김홍철', 'NO홍철'],
    keyword: 'ㅅㅎㄹㄷㅎNOㅎㅊ',
    episodeNum: 274,
    episodeDate: '2011년 11월 5일',
    episodeName: '수학능력평가 특집',
  },
  {
    title: '무슨 삼만원 나왔어야?',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-040.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-040.png?raw=true',
    cast: ['길'],
    tags: ['질문', '영어', '삼만원'],
    keyword: 'ㅁㅅㅅㅁㅇㄴㅇㅇㅇ?',
    episodeNum: 182,
    episodeDate: '2009년 12월 5일',
    episodeName: '뉴욕 특집-악마는 구리다를 입는다',
  },
  {
    title: '오? 쉽지 않은데?',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-041.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-041.png?raw=true',
    cast: ['박명수'],
    tags: ['어려움', '눈치'],
    keyword: 'ㅇㅅㅈㅇㅇㄷ',
    episodeNum: 487,
    episodeDate: '2016년 7월 2일',
    episodeName: '유재석으로 살기 VS 박명수로 살기',
  },
  {
    title: '모자라면서 나쁜 친구야!',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-042.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-042.png?raw=true',
    cast: ['박명수'],
    tags: ['친구', '우정', '일침'],
    keyword: 'ㅁㅈㄹㅁㅅㄴㅃㅊㄱㅇ',
    episodeNum: 270,
    episodeDate: '2011년 10월 8일',
    episodeName: '무한상사 특집',
  },
  {
    title: '자네는 누가 뽑았나?',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-043.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-043.png?raw=true',
    cast: ['유재석'],
    tags: ['의문', '팀원'],
    keyword: 'ㅈㄴㄴㄴㄱㅃㅇㄴ',
    episodeNum: 479,
    episodeDate: '2016년 5월 7일',
    episodeName: '2016 무한상사',
  },
  {
    title: '계속 술만 마셨어 그냥',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-044.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-044.png?raw=true',
    cast: ['유재석'],
    tags: ['증언', '술'],
    keyword: 'ㄱㅅㅅㅁㅁㅅㅇㄱㄴ',
    episodeNum: 392,
    episodeDate: '2014년 8월 16일',
    episodeName: '도둑들',
  },
  {
    title: '오! 마이! 갓!',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-045.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-045.png?raw=true',
    cast: ['유재석'],
    tags: ['리액션', '오마이갓', 'OMG'],
    keyword: 'ㅇㅁㅇㄱ',
    episodeNum: 312,
    episodeDate: '2013년 1월 12일',
    episodeName: '뉴욕스타일',
  },
  {
    title: '멤버들 다시 짠다!!',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-046.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-046.png?raw=true',
    cast: ['유재석'],
    tags: ['다짐', '멤버', '팀장'],
    keyword: 'ㅁㅁㄷㄷㅅㅉㄷ',
    episodeNum: 392,
    episodeDate: '2014년',
    episodeName: '도둑들',
  },
  {
    title: '내가 들었던 것 중에 최악이야',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-047.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-047.png?raw=true',
    cast: ['유재석'],
    tags: ['최악', '경고', '일침'],
    keyword: 'ㄴㄱㄷㅇㄷㄱㅈㅇㅊㅇㅇㅇ',
    episodeNum: 345,
    episodeDate: '2013년 8월 31일',
    episodeName: '무한도전 응원단',
  },
  {
    title: '저한테 왜 이러세요',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-048.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-048.png?raw=true',
    cast: ['유재석'],
    tags: ['부담', '두려움'],
    keyword: 'ㅈㅎㅌㅇㅇㄹㅅㅇ',
    episodeNum: 368,
    episodeDate: '2014년 2월 8일',
    episodeName: '무도 탐정 사무소',
  },
  {
    title: '느아아아아아~',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-049.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-049.png?raw=true',
    cast: ['유재석'],
    tags: ['조롱', '식신', '식사'],
    keyword: 'ㄴㅇㅇㅇㅇㅇ',
    episodeNum: 173,
    episodeDate: '2009년 10월 3일',
    episodeName: '무한도전 TV',
  },
  {
    title: '본 건 있으나 모자란 기억력',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-050.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-050.png?raw=true',
    cast: ['정형돈'],
    tags: ['기억력', '모자람'],
    keyword: 'ㅂㄱㅇㅇㄴㅁㅈㄹㄱㅇㄹ',
    episodeNum: 368,
    episodeDate: '2월',
    episodeName: '무도 탐정 사무소',
  },
  {
    title: '한계임박',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-051.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-051.png?raw=true',
    cast: ['유재석'],
    tags: ['분노', '대노', '화남', '한계임박'],
    keyword: 'ㅎㄱㅇㅂ',
    episodeNum: 284,
    episodeDate: '2012년 1월 14일',
    episodeName: '무한상사 신년맞이 특집',
  },
  {
    title: '이게 뭐 하는 거야 지금',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-052.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-052.png?raw=true',
    cast: ['유재석'],
    tags: ['황당', '어이없음', '뭐야'],
    keyword: 'ㅇㄱㅁㅎㄴㄱㅇㅈㄱ',
    episodeNum: 389,
    episodeDate: '2014년 7월 26일',
    episodeName: '방콕 특집',
  },
  {
    title: '세상은 1등만 기억해',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-053.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-053.png?raw=true',
    cast: ['박명수'],
    tags: ['1등', '불공평한 세상'],
    keyword: 'ㅅㅅㅇ1ㄷㅁㄱㅇㅎ',
    episodeNum: 369,
    episodeDate: '2014년 2월 22일',
    episodeName: '자메이카 특집',
  },
  {
    title: '밥은 먹고 다니니?',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-054.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-054.png?raw=true',
    cast: ['박명수'],
    tags: ['밥', '식사', '영상편지', '안부'],
    keyword: 'ㅂㅇㅁㄱㄷㄴㄴ',
    episodeNum: 83,
    episodeDate: '2007년 12월 15일',
    episodeName: '달력 만들기 특집',
  },
  {
    title: '입만 벙긋해도 현실로',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-055.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-055.png?raw=true',
    cast: ['하하', '유재석', '박명수'],
    tags: ['입조심', '벙긋'],
    keyword: 'ㅇㅁㅂㄱㅎㄷㅎㅅㄹ',
    episodeNum: 237,
    episodeDate: '2011년 2월 19일',
    episodeName: '오호츠크해 특집',
  },
  {
    title: '어 대박이다',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-056.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-056.png?raw=true',
    cast: ['유재석'],
    tags: ['대박', '허걱', '놀람'],
    keyword: 'ㅇㄷㅂㅇㄷ',
    episodeNum: 483,
    episodeDate: '2016년 6월 4일',
    episodeName: '릴레이툰',
  },
  {
    title: '잠을 자도 피로가 안 풀리냐',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-057.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-057.png?raw=true',
    cast: ['박명수'],
    tags: ['직장인', '학생', '피로', '피곤', '짜증'],
    keyword: 'ㅈㅇㅈㄷㅍㄹㄱㅇㅍㄹㄴ',
    episodeNum: 270,
    episodeDate: '2011년 10월 8일',
    episodeName: '무한상사 특집',
  },
  {
    title: '스트레스 한가득',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-058.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-058.png?raw=true',
    cast: ['정형돈'],
    tags: ['스트레스', '피곤', '힘듦'],
    keyword: 'ㅅㅌㄹㅅㅎㄱㄷ',
    episodeNum: 321,
    episodeDate: '2013년 3월 16일',
    episodeName: 'NO 스트레스',
  },
  {
    title: '누굴 보자기로 아나!!',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-059.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-059.png?raw=true',
    cast: ['정준하'],
    tags: ['분노', '대노', '보자기', '화남'],
    keyword: 'ㄴㄱㅂㅈㄱㄹㅇㄴ',
    episodeNum: 327,
    episodeDate: '2013년 4월 27일',
    episodeName: '무한상사 뮤지컬',
  },
  {
    title: '변사체가 아니고 변싼체',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-060.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-060.png?raw=true',
    cast: ['유재석', '박명수'],
    tags: ['특종', '변싼체', '놀림'],
    keyword: 'ㅂㅅㅊㄱㅇㄴㄱㅂㅆㅊ',
    episodeNum: 182,
    episodeDate: '2009년 12월 12일',
    episodeName: '뉴욕특집-악마는 구리다를 입는다',
  },
  {
    title: '짜잔',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-061.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-061.png?raw=true',
    cast: ['박명수'],
    tags: ['짜잔', '회식'],
    keyword: 'ㅉㅈ',
    episodeNum: 284,
    episodeDate: '2012년 1월 14일',
    episodeName: '무한상사 신년맞이 특집',
  },
  {
    title: '이거 사이버 머니 조심해요',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-062.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-062.png?raw=true',
    cast: ['유재석'],
    tags: ['회사', '사이버 머니', '조심'],
    keyword: 'ㅇㄱㅅㅇㅂㅁㄴㅈㅅㅎㅇ',
    episodeNum: 270,
    episodeDate: '2011년 10월 8일',
    episodeName: '무한상사 특집',
  },
  {
    title: '미모만이 경쟁력은 아닙니다',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-063.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-063.png?raw=true',
    cast: ['유재석'],
    tags: ['공주', '미모', '경쟁력'],
    keyword: 'ㅁㅁㅁㅇㄱㅈㄹㅇㅇㄴㄴㄷ',
    episodeNum: 340,
    episodeDate: '2013년 7월 27일',
    episodeName: '소문난 칠공주',
  },
  {
    title: '방긋',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-064.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-064.png?raw=true',
    cast: ['길'],
    tags: ['방긋', '미소'],
    keyword: 'ㅂㄱ',
    episodeNum: 210,
    episodeDate: '2010년 8월 7일',
    episodeName: '아이돌 특집',
  },
  {
    title: '우리 무한도전…',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-065.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-065.png?raw=true',
    cast: ['길'],
    tags: ['진땀', '당황', '달마'],
    keyword: 'ㅇㄹㅁㅎㄷㅈ',
    episodeNum: 153,
    episodeDate: '2009년 5월 9일',
    episodeName: '춘향뎐 특집',
  },
  {
    title: '다 미쳤어…',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-066.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-066.png?raw=true',
    cast: ['노홍철'],
    tags: ['헐크호건', '놀람', '충격'],
    keyword: 'ㄷㅁㅊㅇ',
    episodeNum: 183,
    episodeDate: '2009년 12월 12일',
    episodeName: '2010 달력만들기 특집',
  },
  {
    title: '전 안 되겠어요',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-067.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-067.png?raw=true',
    cast: ['노홍철'],
    tags: ['광기', '포기', '다이어트', '단거', '울분'],
    keyword: 'ㅈㅇㄷㄱㅇㅇ',
    episodeNum: 199,
    episodeDate: '2010년 5월 22일',
    episodeName: '신년특집 다이어트 최종결과',
  },
  {
    title: '뭐라고?',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-068.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-068.png?raw=true',
    cast: ['노홍철'],
    tags: ['무라고', '타령', '광기'],
    keyword: 'ㅁㄹㄱ',
    episodeNum: 298,
    episodeDate: '2012년 10월 6일',
    episodeName: '행쇼',
  },
  {
    title: '웃어서 행복한 겁니다',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-069.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-069.png?raw=true',
    cast: ['노홍철'],
    tags: ['긍정', '웃음', '행복', '광기'],
    keyword: 'ㅇㅇㅅㅎㅂㅎㄱㄴㄷ',
    episodeNum: 238,
    episodeDate: '2011년 2월 26일',
    episodeName: '오호츠크해 특집',
  },
  {
    title: '형! 개처럼 파시네요',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-070.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-070.png?raw=true',
    cast: ['노홍철'],
    tags: ['비유', '개'],
    keyword: 'ㅎㄱㅊㄹㅍㅅㄴㅇ',
    episodeNum: 195,
    episodeDate: '2010년 3월 6일',
    episodeName: '오 마이 텐트 특집',
  },
  {
    title: '받아들이기 힘든 현실',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-071.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-071.png?raw=true',
    cast: ['박명수'],
    tags: ['현실', '실망', '부정'],
    keyword: 'ㅂㅇㄷㅇㄱㅎㄷㅎㅅ',
    episodeNum: 13,
    episodeDate: '2006년 8월 5일',
    episodeName: '납량 특집',
  },
  {
    title: '알게 뭐야 지금 내가 신나는데',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-072.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-072.png?raw=true',
    cast: ['박명수'],
    tags: ['신남', '웃음', '행복', '자기만족'],
    keyword: 'ㅇㄱㅁㅇㅈㄱㄴㄱㅅㄴㄴㄷ',
    episodeNum: 526,
    episodeDate: '2017년 4월 22일',
    episodeName: '2018 평창',
  },
  {
    title: '쀠로리',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-073.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-073.png?raw=true',
    cast: ['하하'],
    tags: ['영어', '빅토리', '무식'],
    keyword: 'ㅃㄹㄹ',
    episodeNum: 274,
    episodeDate: '2011년 11월 5일',
    episodeName: '수학능력평가 특집',
  },
  {
    title: '어흐 피곤해! 어흐 어흐으',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-074.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-074.png?raw=true',
    cast: ['박명수'],
    tags: ['피로', '피곤', '하품', '직장인', '학생'],
    keyword: 'ㅇㅎㅍㄱㅎㅇㅎㅇㅎㅇ',
    episodeNum: 548,
    episodeDate: '2017년 12월 9일',
    episodeName: '2018 수학능력시험',
  },
  {
    title: '화끈하게 놀아보자',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-075.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-075.png?raw=true',
    cast: ['박명수'],
    tags: ['여행', '약속', '다짐', '화끈'],
    keyword: 'ㅎㄲㅎㄱㄴㅇㅂㅈ',
    episodeNum: 302,
    episodeDate: '2012년 11월 3일',
    episodeName: '언니의 유혹',
  },
  {
    title: '나 지금 이 현실 믿기지 않아요',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-076.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-076.png?raw=true',
    cast: ['유재석'],
    tags: ['어이없음', '황당'],
    keyword: 'ㄴㅈㄱㅇㅎㅅㅁㄱㅈㅇㅇㅇ',
    episodeNum: 204,
    episodeDate: '2010년 6월 26일',
    episodeName: '자리분양 특집',
  },
  {
    title: '남녀평등 & 두발 자유화',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-077.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-077.png?raw=true',
    cast: ['하하'],
    tags: ['선언', '남녀평등', '두발자유'],
    keyword: 'ㄴㄴㅍㄷㄷㅂㅈㅇㅎ',
    episodeNum: 297,
    episodeDate: '2012년 9월 29일',
    episodeName: '추석특집 무한상사',
  },
  {
    title: '정신차려 이 각박한 세상 속에서',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-078.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-078.png?raw=true',
    cast: ['하하'],
    tags: ['이름', '삿대질', '정신차려'],
    keyword: 'ㅈㅅㅍㄹㅇㄱㅂㅎㅅㅅㅅㅇㅅ',
    episodeNum: 298,
    episodeDate: '2012년 10월 6일',
    episodeName: '추석특집 무한상사',
  },
  {
    title: '전 눈물이 안 나요',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-079.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-079.png?raw=true',
    cast: ['박명수'],
    tags: ['말짱', '눈물'],
    keyword: 'ㅈㄴㅁㅇㅇㄴㅇ',
    episodeNum: 82,
    episodeDate: '2007년 12월 8일',
    episodeName: '쉘위댄스 특집',
  },
  {
    title: '아이고 미안합니다',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-080.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-080.png?raw=true',
    cast: ['박명수'],
    tags: ['미안', '사과'],
    keyword: 'ㅇㅇㄱㅁㅇㅎㄴㄷ',
    episodeNum: 175,
    episodeDate: '2009년 10월 17일',
    episodeName: '벼농사 특집',
  },
  {
    title: '대다나다',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-081.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-081.png?raw=true',
    cast: ['정준하', '박명수'],
    tags: ['리액션', '대단하다', '놀람'],
    keyword: 'ㄷㄷㄴㄷ',
    episodeNum: 333,
    episodeDate: '2013년 6월 8일',
    episodeName: '행쇼',
  },
  {
    title: '충격',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-082.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-082.png?raw=true',
    cast: ['정준하'],
    tags: ['충격', '놀람', '헉'],
    keyword: 'ㅊㄱ',
    episodeNum: 250,
    episodeDate: '2011년 5월 21일',
    episodeName: '무한상사 야유회',
  },
  {
    title: '문화 충격으로 아노미 상태',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-083.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-083.png?raw=true',
    cast: ['노홍철'],
    tags: ['충격', '놀람'],
    keyword: 'ㅁㅎㅊㄱㅇㄹㅇㄴㅁㅅㅌ',
    episodeNum: 389,
    episodeDate: '2014년 7월 26일',
    episodeName: '방콕 특집',
  },
  {
    title: '잘 있었어?',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-084.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-084.png?raw=true',
    cast: ['노홍철'],
    tags: ['인사', '광기', '자기애'],
    keyword: 'ㅈㅇㅇㅇ',
    episodeNum: 339,
    episodeDate: '2013년 7월 20일',
    episodeName: '완전 남자다잉',
  },
  {
    title: '말을 잇지 못하는',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-085.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-085.png?raw=true',
    cast: ['유재석'],
    tags: ['충격', '말잇못', '파마', '놀람'],
    keyword: 'ㅁㅇㅇㅈㅁㅎㄴ',
    episodeNum: 74,
    episodeDate: '2007년 10월 6일',
    episodeName: '가을 운동회',
  },
  {
    title: '추억이 어딨니 먹고 살기 힘든데',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-086.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-086.png?raw=true',
    cast: ['박명수'],
    tags: ['퉁명', '어쩌라고', '추억'],
    keyword: 'ㅊㅇㅇㅇㄷㄴㅁㄱㅅㄱㅎㄷㄷ',
    episodeNum: 168,
    episodeDate: '2009년 8월 29일',
    episodeName: '여름방학 특집',
  },
  {
    title: '에구머니나',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-087.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-087.png?raw=true',
    cast: ['하하'],
    tags: ['머쓱', '놀람', '웃음'],
    keyword: 'ㅇㄱㅁㄴㄴ',
    episodeNum: 302,
    episodeDate: '2012년 11월 3일',
    episodeName: '언니의 유혹',
  },
  {
    title: '그래 이 맛이야',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-088.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-088.png?raw=true',
    cast: ['하하'],
    tags: ['먹방', '행복', '리액션'],
    keyword: 'ㄱㄹㄴㅁㅇㅇ',
    episodeNum: 302,
    episodeDate: '2012년 11월 3일',
    episodeName: '언니의 유혹',
  },
  {
    title: '밥줘!',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-089.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-089.png?raw=true',
    cast: ['박명수'],
    tags: ['밥', '호통', '명령'],
    keyword: 'ㅂㅈ',
    episodeNum: 174,
    episodeDate: '2009년 10월 10일',
    episodeName: '무한도전TV',
  },
  {
    title: '쟤 때리고 빵 가?',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-090.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-090.png?raw=true',
    cast: ['박명수'],
    tags: ['욱', '짜증', '화남'],
    keyword: 'ㅈㄸㄹㄱㅃㄱ',
    episodeNum: 435,
    episodeDate: '2015년 7월 4일',
    episodeName: '무한도전 가요제 - 가면 무도회',
  },
  {
    title: '아주 주접을 떠는구나… 아주 그냥',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-091.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-091.png?raw=true',
    cast: ['박명수'],
    tags: ['훈수', '주접', '비난'],
    keyword: 'ㅇㅈㅈㅈㅇㄸㄴㄱㄴㅇㅈㄱㄴ',
    episodeNum: 425,
    episodeDate: '2015년 4월 25일',
    episodeName: '10주년 앙케트 특집',
  },
  {
    title: '무소식이 희소식이야!!',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-092.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-092.png?raw=true',
    cast: ['박명수'],
    tags: ['호통', '짜증'],
    keyword: 'ㅁㅅㅅㅇㅎㅅㅅㅇㅇ',
    episodeNum: 487,
    episodeDate: '2016년 7월 2일',
    episodeName: '릴레이 툰',
  },
  {
    title: '우이쒸~!',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-093.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-093.png?raw=true',
    cast: ['유재석'],
    tags: ['우이쒸'],
    keyword: 'ㅇㅇㅆ',
    episodeNum: 69,
    episodeDate: '2007년 9월 1일',
    episodeName: '네 멋대로 해라',
  },
  {
    title: '돌아와 줘요',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-094.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-094.png?raw=true',
    cast: ['박명수'],
    tags: ['사과', '부탁', '바램'],
    keyword: 'ㄷㅇㅇㅈㅇ',
    episodeNum: 24,
    episodeDate: '2006년 10월 21일',
    episodeName: '가을소풍 특집',
  },
  {
    title: '하지마',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-095.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-095.png?raw=true',
    cast: ['박명수'],
    tags: ['하지마', '경고', '단호'],
    keyword: 'ㅎㅈㅁ',
    episodeNum: 418,
    episodeDate: '2015년 3월 7일',
    episodeName: '무도 어린이집',
  },
  {
    title: '싫은데!!',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-096.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-096.png?raw=true',
    cast: ['정형돈'],
    tags: ['싫은데', '청개구리'],
    keyword: 'ㅅㅇㄷ',
    episodeNum: 326,
    episodeDate: '2013년 4월 20일',
    episodeName: '명수는 12살',
  },
  {
    title: '이건 뭐하러 들고 다니냐?!!',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-097.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-097.png?raw=true',
    cast: ['정형돈'],
    tags: ['짜증', '비난', '의문'],
    keyword: 'ㅇㄱㅁㅎㄹㄷㄱㄷㄴㄴ',
    episodeNum: 284,
    episodeDate: '2012년 1월 14일',
    episodeName: '무한상사 신년맞이 특집',
  },
  {
    title: '여름 너무 더워',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-098.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-098.png?raw=true',
    cast: ['정형돈'],
    tags: ['짜증', '여름', '더위'],
    keyword: 'ㅇㄹㄴㅁㄷㅇ',
    episodeNum: 160,
    episodeDate: '2009년 7월 4일',
    episodeName: '올림픽대로 듀엣 가요제 특집',
  },
  {
    title: '아이고',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-099.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-099.png?raw=true',
    cast: ['정형돈'],
    tags: ['아이고', '탄식', '한숨'],
    keyword: 'ㅇㅇㄱ',
    episodeNum: 299,
    episodeDate: '2012년 10월 13일',
    episodeName: '新햇님달님',
  },
  {
    title: '제 열정이 이 정도입니다',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-100.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-100.png?raw=true',
    cast: ['박명수'],
    tags: ['열정', '스트레칭', '의지'],
    keyword: 'ㅈㅇㅈㅇㅇㅈㄷㅇㄴㄷ',
    episodeNum: 479,
    episodeDate: '2016년 5월 7일',
    episodeName: '2016 무한상사',
  },
  {
    title: '살이나 팍팍 쪄라 한 5kg 쪄라',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-101.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-101.png?raw=true',
    cast: ['정준하'],
    tags: ['비난', '저주', '악담'],
    keyword: 'ㅅㅇㄴㅍㅍㅉㄹㅎ5kgㅉㄹ',
    episodeNum: 91,
    episodeDate: '2008년 2월 9일',
    episodeName: '특전사 혹한기 훈련',
  },
  {
    title: '지금 뭐 하는 거야?',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-102.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-102.png?raw=true',
    cast: ['유재석'],
    tags: ['짜증'],
    keyword: 'ㅈㄱㅁㅎㄴㄱㅇ',
    episodeNum: 430,
    episodeDate: '2015년 5월 30일',
    episodeName: '해외 극한알바',
  },
  {
    title: '귀여운 건 나도 알아',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-103.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-103.png?raw=true',
    cast: ['박명수'],
    tags: ['귀여움', '자기애'],
    keyword: 'ㄱㅇㅇㄱㄴㄷㅇㅇ',
    episodeNum: 337,
    episodeDate: '2013년 7월 6일',
    episodeName: '웃겨야 산다!',
  },
  {
    title: '이 구역의 공주는 나다',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-104.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-104.png?raw=true',
    cast: ['길'],
    tags: ['공주', '오랑우탄', '미모'],
    keyword: 'ㅇㄱㅇㅇㄱㅈㄴㄴㄷ',
    episodeNum: 340,
    episodeDate: '2013년 7월 27일',
    episodeName: '소문난 칠공주',
  },
  {
    title: '뭐요!',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-105.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-105.png?raw=true',
    cast: ['정형돈'],
    tags: ['취함', '뭐', '진상', '딸꾹'],
    keyword: 'ㅁㅇ',
    episodeNum: 250,
    episodeDate: '2011년 5월 21일',
    episodeName: '무한상사 야유회',
  },
  {
    title: '지금 나 되게 황당하다',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-106.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-106.png?raw=true',
    cast: ['유재석'],
    tags: ['황당', '어이없음'],
    keyword: 'ㅈㄱㄴㄷㄱㅎㄷㅎㄷ',
    episodeNum: 49,
    episodeDate: '2007년 4월 14일',
    episodeName: '행사 하나마나',
  },
  {
    title: '못이기는 척하고 하겠습니다',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-107.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-107.png?raw=true',
    cast: ['유재석'],
    tags: ['유쾌', '웃음', '당선', '소감'],
    keyword: 'ㅁㅇㄱㄴㅊㅎㄱㅎㄱㅅㄴㄷ',
    episodeNum: 317,
    episodeDate: '2013년 2월 16일',
    episodeName: '맞짱',
  },
  {
    title: '진심이야?',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-108.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-108.png?raw=true',
    cast: ['정준하'],
    tags: ['의문', '의심', '진심'],
    keyword: 'ㅈㅅㅇㅇ',
    episodeNum: 279,
    episodeDate: '2011년 12월 10일',
    episodeName: '명수는 12살',
  },
  {
    title: '며칠 서 계셔가지고',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-109.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-109.png?raw=true',
    cast: ['정준하'],
    tags: ['이유', '궁시렁'],
    keyword: 'ㅁㅊㅅㄱㅅㄱㅈㄱ',
    episodeNum: 326,
    episodeDate: '2013년 4월 20일',
    episodeName: '',
  },
  {
    title: '돌+아이',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-110.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-110.png?raw=true',
    cast: ['노홍철'],
    tags: ['돌아이', '또라이', '광기'],
    keyword: 'ㄷ+ㅇㅇ',
    episodeNum: 56,
    episodeDate: '2007년 6월 2일',
    episodeName: '모내기 특집',
  },
  {
    title: '제 여자친구 장윤정입니다',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-111.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-111.png?raw=true',
    cast: ['노홍철'],
    tags: ['여자친구', '장윤정'],
    keyword: 'ㅈㅇㅈㅊㄱㅈㅇㅈㅇㄴㄷ',
    episodeNum: 182,
    episodeDate: '2009년 12월 5일',
    episodeName: '뉴욕특집 - 악마는 구리다를 입는다',
  },
  {
    title: '꼭꼭 감추면 이게 자식입니까',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-112.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-112.png?raw=true',
    cast: ['노홍철'],
    tags: ['약속', '공개', '호소', '광기'],
    keyword: 'ㄲㄲㄱㅊㅁㅇㄱㅈㅅㅇㄴㄲ',
    episodeNum: 377,
    episodeDate: '2014년 5월 3일',
    episodeName: '선택 2014',
  },
  {
    title: '물러가라',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-113.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-113.png?raw=true',
    cast: ['노홍철'],
    tags: ['광기', '호통', '물러가라'],
    keyword: 'ㅁㄹㄱㄹ',
    episodeNum: 377,
    episodeDate: '2014년 5월 3일',
    episodeName: '선택 2014',
  },
  {
    title: '난 커서 아무것도 안 될 거야',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-114.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-114.png?raw=true',
    cast: ['노홍철'],
    tags: ['자책', '한탄'],
    keyword: 'ㄴㅋㅅㅇㅁㄱㄷㅇㄷㄱㅇ',
    episodeNum: 326,
    episodeDate: '2013년 4월 20일',
    episodeName: '명수는 12살',
  },
  {
    title: '말 많아',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-115.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-115.png?raw=true',
    cast: ['노홍철'],
    tags: ['말많아', '박수', '수다'],
    keyword: 'ㅁㅁㅇ',
    episodeNum: 40,
    episodeDate: '2007년 2월 10일',
    episodeName: '알래스카 특집',
  },
  {
    title: '사람 잠못보진 것 같은…',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-116.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-116.png?raw=true',
    cast: ['노홍철'],
    tags: ['광기', '오해', '닮은꼴'],
    keyword: 'ㅅㄹㅈㅁㅂㅈㄱㄱㅇ',
    episodeNum: 141,
    episodeDate: '2009년 2월 14일',
    episodeName: '쪽대본 드라마 특집',
  },
  {
    title: 'ADHD 집중력 장애',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-117.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-117.png?raw=true',
    cast: ['노홍철'],
    tags: ['ADHD', '집중력 장애'],
    keyword: 'ADHDㅈㅈㄹㅈㅇ',
    episodeNum: 143,
    episodeDate: '2009년 2월 28일',
    episodeName: '정신감정 특집',
  },
  {
    title: '날 동정하지 마세요',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-118.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-118.png?raw=true',
    cast: ['노홍철'],
    tags: ['대머리', '동정'],
    keyword: 'ㄴㄷㅈㅎㅈㅁㅅㅇ',
    episodeNum: 199,
    episodeDate: '2010년 5월 22일',
    episodeName: '신년특집 다이어트 최종결과',
  },
  {
    title: '잠복기 지나 제철 맞은 매콤함',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-119.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-119.png?raw=true',
    cast: ['길'],
    tags: ['외계인', '진땀'],
    keyword: 'ㅈㅂㄱㅈㄴㅈㅊㅁㅇㅁㅋㅎ',
    episodeNum: 372,
    episodeDate: '2014년 3월 15일',
    episodeName: '지구를 지켜라',
  },
  {
    title: '김경식 씨…',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-120.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-120.png?raw=true',
    cast: ['길'],
    tags: ['엮은이', '김경식'],
    keyword: 'ㄱㄱㅅㅆ',
    episodeNum: 297,
    episodeDate: '2012년 9월 29일',
    episodeName: '추석특집 무한상사',
  },
  {
    title: '소주 하나 주세요',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-121.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-121.png?raw=true',
    cast: ['길'],
    tags: ['주문', '소주'],
    keyword: 'ㅅㅈㅎㄴㅈㅅㅇ',
    episodeNum: 208,
    episodeDate: '2010년 7월 24일',
    episodeName: '시크릿 바캉스',
  },
  {
    title: '길 잃은 토크',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-122.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-122.png?raw=true',
    cast: ['길'],
    tags: ['토크', '어이없음', '웃음'],
    keyword: 'ㄱㅇㅇㅌㅋ',
    episodeNum: 262,
    episodeDate: '2011년 8월 13일',
    episodeName: '우천시 취소 특집',
  },
  {
    title: '가관이네 가관이야',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-123.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-123.png?raw=true',
    cast: ['길'],
    tags: ['가관', '장관'],
    keyword: 'ㄱㄱㅇㄴㄱㄱㅇㅇ',
    episodeNum: 221,
    episodeDate: '2010년 10월 23일',
    episodeName: '텔레파시 특집',
  },
  {
    title: '풍월을 울려라',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-124.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-124.png?raw=true',
    cast: ['길'],
    tags: ['풍악', '풍월', '임금님', '명령'],
    keyword: 'ㅍㅇㅇㅇㄹㄹ',
    episodeNum: 153,
    episodeDate: '2009년 5월 9일',
    episodeName: '춘향뎐 특집',
  },
  {
    title: '민서까지?',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-125.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-125.png?raw=true',
    cast: ['길'],
    tags: ['놀람', '굳이?', '민서'],
    keyword: 'ㅁㅅㄲㅈ',
    episodeNum: 328,
    episodeDate: '2013년 5월 4일',
    episodeName: '2013 빙고',
  },
  {
    title: '빠져라',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-126.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-126.png?raw=true',
    cast: ['박명수'],
    tags: ['빠져라', '충고', '진심'],
    keyword: 'ㅃㅈㄹ',
    episodeNum: 270,
    episodeDate: '2011년 10월 8일',
    episodeName: '무한상사 특집',
  },
  {
    title: '장생농씬가?',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-127.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-127.png?raw=true',
    cast: ['길'],
    tags: ['장생농', '질문'],
    keyword: 'ㅈㅅㄴㅆㄱ',
    episodeNum: 238,
    episodeDate: '2011년 2월 26일',
    episodeName: '오호츠크해 특집',
  },
  {
    title: '나 파인애플',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-128.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-128.png?raw=true',
    cast: ['길'],
    tags: ['개인기', '파인애플', '웃음'],
    keyword: 'ㄴㅍㅇㅇㅍ',
    episodeNum: 176,
    episodeDate: '2009년 10월 24일',
    episodeName: '벼농사 특집',
  },
  {
    title: '12세 치곤 심하게 당한 길이',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-129.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-129.png?raw=true',
    cast: ['길'],
    tags: ['부상', '상처', '아픔'],
    keyword: '12ㅅㅊㄱㅅㅎㄱㄷㅎㄱㅇ',
    episodeNum: 279,
    episodeDate: '2011년 12월 10일',
    episodeName: '명수는 12살',
  },
  {
    title: '한 시라도 빨리 널 보고파…',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-130.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-130.png?raw=true',
    cast: ['노홍철'],
    tags: ['광기', '애인', '그리움'],
    keyword: 'ㅎㅅㄹㄷㅃㄹㄴㅂㄱㅍ',
    episodeNum: 162,
    episodeDate: '2009년 7월 18일',
    episodeName: '2010 달력 만들기 특집',
  },
  {
    title: '넌 내 상대가 아니야!',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-131.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-131.png?raw=true',
    cast: ['정준하'],
    tags: ['발차기', '꺼져', '비켜'],
    keyword: 'ㄴㄴㅅㄷㄱㅇㄴㅇ',
    episodeNum: 290,
    episodeDate: '2012년 8월 11일',
    episodeName: '개그학개론',
  },
  {
    title: '우리 할아버진 할머니가 두 분이셨어',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-132.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-132.png?raw=true',
    cast: ['길'],
    tags: ['고백', '덤덤', '할아버지', '할머니'],
    keyword: 'ㅇㄹㅎㅇㅂㅈㅎㅁㄴㄱㄷㅂㅇㅆㅇ',
    episodeNum: 278,
    episodeDate: '2011년 12월 3일',
    episodeName: '명수는 12살',
  },
  {
    title: '길북이 탄생!',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-133.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-133.png?raw=true',
    cast: ['길'],
    tags: ['거북이', '대머리', '동물'],
    keyword: 'ㄱㅂㅇㅌㅅ',
    episodeNum: 218,
    episodeDate: '2010년 10월 2일',
    episodeName: '도전! 달력모델',
  },
  {
    title: '남자는 미쳤다',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-134.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-134.png?raw=true',
    cast: ['박명수'],
    tags: ['이행시', '남미'],
    keyword: 'ㄴㅈㄴㅁㅊㄷ',
    episodeNum: 445,
    episodeDate: '2015년 9월 5일',
    episodeName: '배달의 무도',
  },
  {
    title: '바나나맛 우유 그만 먹으라고',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-135.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-135.png?raw=true',
    cast: ['길'],
    tags: ['짜증', '경고', '제발'],
    keyword: 'ㅂㄴㄴㅁㅇㅇㄱㅁㅁㅇㄹㄱ',
    episodeNum: 207,
    episodeDate: '2010년 7월 17일',
    episodeName: '시크릿 바캉스',
  },
  {
    title: '이러다 숨넘어갈라…',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-136.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-136.png?raw=true',
    cast: ['길'],
    tags: ['웃음', '유쾌'],
    keyword: 'ㅇㄹㄷㅅㄴㅇㄱㄹ',
    episodeNum: 163,
    episodeDate: '2009년 7월 25일',
    episodeName: 'SOS 해양구조대 특집',
  },
  {
    title: '어~! 너무 하잖아요!',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-137.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-137.png?raw=true',
    cast: ['길'],
    tags: ['호소', '한탄', '너무해'],
    keyword: 'ㅇㄴㅁㅎㅈㅇㅇ',
    episodeNum: 231,
    episodeDate: '2011년 1월 8일',
    episodeName: '정총무가 쏜다',
  },
  {
    title: '네버 세이 굿바이',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-138.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-138.png?raw=true',
    cast: ['정준하'],
    tags: ['노래', '가창력'],
    keyword: 'ㄴㅂㅅㅇㄱㅂㅇ',
    episodeNum: 311,
    episodeDate: '2013년 1월 5일',
    episodeName: '박명수의 어떤가요',
  },
  {
    title: '여기 망했어요~~',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-139.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-139.png?raw=true',
    cast: ['길'],
    tags: ['전화', '망함', '호소'],
    keyword: 'ㅇㄱㅁㅎㅇㅇ',
    episodeNum: 196,
    episodeDate: '2010년 3월 13일',
    episodeName: '오 마이 텐트 특집',
  },
  {
    title: '아무 말 없이 안아주는 두 사람',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-140.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-140.png?raw=true',
    cast: ['길', '정준하'],
    tags: ['감동', '포옹', '격려'],
    keyword: 'ㅇㅁㅁㅇㅇㅇㅇㅈㄴㄷㅅㄹ',
    episodeNum: 472,
    episodeDate: '2016년 3월 18일',
    episodeName: '힙합의 神 MC민지',
  },
  {
    title: '이걸 국괴수에 보내겠습니다',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-141.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-141.png?raw=true',
    cast: ['길'],
    tags: ['무식', '법정', '증거물'],
    keyword: 'ㅇㄱㄱㄱㅅㅇㅂㄴㄱㅅㄴㄷ',
    episodeNum: 194,
    episodeDate: '2010년 2월 27일',
    episodeName: '죄와 길',
  },
  {
    title: '이건 꿈일거야',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-142.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-142.png?raw=true',
    cast: ['길'],
    tags: ['놀람', '우와'],
    keyword: 'ㅇㄱㄲㅇㄱㅇ',
    episodeNum: 332,
    episodeDate: '2013년 6월 1일',
    episodeName: '무한상사 뮤지컬',
  },
  {
    title: '남을 배척하는 매국노야',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-143.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-143.png?raw=true',
    cast: ['박명수'],
    tags: ['비난', '공격', '호통'],
    keyword: 'ㄴㅇㅂㅊㅎㄴㅁㄱㄴㅇ',
    episodeNum: 25,
    episodeDate: '2006년 10월 28일',
    episodeName: '농촌체험 특집',
  },
  {
    title: '부끄러워지는 동생들',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-144.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-144.png?raw=true',
    cast: ['길'],
    tags: ['부끄러움', '웃음'],
    keyword: 'ㅂㄲㄹㅇㅈㄴㄷㅅㄷ',
    episodeNum: 350,
    episodeDate: '2013년 10월 5일',
    episodeName: '무한도전 응원단',
  },
  {
    title: '형수님 냄새가 나서 그러는 거예요',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-145.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-145.png?raw=true',
    cast: ['길', '정준하'],
    tags: ['형수님', '냄새'],
    keyword: 'ㅎㅅㄴㄴㅅㄱㄴㅅㄱㄹㄴㄱㅇㅇ',
    episodeNum: 178,
    episodeDate: '2009년 11월 7일',
    episodeName: '식객 특집',
  },
  {
    title: '야 이걸 내가 살다가 보네!',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-146.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-146.png?raw=true',
    cast: ['길'],
    tags: ['뭔소리', '우와', '신기'],
    keyword: 'ㅇㅇㄱㄴㄱㅅㄷㄱㅂㄴ',
    episodeNum: 182,
    episodeDate: '2009년 12월 5일',
    episodeName: '뉴욕특집 - 악마는 구리다를 입는다',
  },
  {
    title: '3명이니까 4개죠!',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-147.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-147.png?raw=true',
    cast: ['길'],
    tags: ['당당', '야식', '대머리'],
    keyword: '3ㅁㅇㄴㄲ4ㄱㅈ',
    episodeNum: 273,
    episodeDate: '2011년 10월 29일',
    episodeName: '짝궁 특집',
  },
  {
    title: '인기가 있어야 거품이지',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-148.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-148.png?raw=true',
    cast: ['길'],
    tags: ['호통', '인기', '거품'],
    keyword: 'ㅇㄱㄱㅇㅇㅇㄱㅍㅇㅈ',
    episodeNum: 340,
    episodeDate: '2013년 7월 27일',
    episodeName: '소문난 칠공주',
  },
  {
    title: '슬픈 여자요?',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-149.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-149.png?raw=true',
    cast: ['길'],
    tags: ['의문', '사오정'],
    keyword: 'ㅅㅍㅇㅈㅇ',
    episodeNum: 199,
    episodeDate: '2010년 5월 22일',
    episodeName: '예능의 신(神) 특집',
  },
  {
    title: '행복해요',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-150.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-150.png?raw=true',
    cast: ['길'],
    tags: ['행복', '웃음'],
    keyword: 'ㅎㅂㅎㅇ',
    episodeNum: 188,
    episodeDate: '2010년 1월 16일',
    episodeName: '',
  },
  {
    title: '네가 날 좋아하는데 난 몰라',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-151.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-151.png?raw=true',
    cast: ['하하'],
    tags: ['컨셉', '희망사항'],
    keyword: 'ㄴㄱㄴㅈㅇㅎㄴㄷㄴㅁㄹ',
    episodeNum: 63,
    episodeDate: '2007년 7월 21일',
    episodeName: '방송국 24시 & 복날 특집',
  },
  {
    title: '조금 더 노력을 해줬으면 좋겠어',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-152.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-152.png?raw=true',
    cast: ['하하'],
    tags: ['노력', '진지함', '충고'],
    keyword: 'ㅈㄱㄷㄴㄹㅇㅎㅈㅇㅁㅈㄱㅇ',
    episodeNum: 486,
    episodeDate: '2016년 6월 25일',
    episodeName: '릴레이 툰',
  },
  {
    title: '집에 가면 개 표정이 딱 저 표정',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-153.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-153.png?raw=true',
    cast: ['하하'],
    tags: ['빌드업', '표정', '비난'],
    keyword: 'ㅈㅇㄱㅁㄱㅍㅈㅇㄸㅈㅍㅈ',
    episodeNum: 226,
    episodeDate: '2010년 12월 4일',
    episodeName: '2011 도전! 달력모델',
  },
  {
    title: '날 가져봐',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-154.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-154.png?raw=true',
    cast: ['하하'],
    tags: ['자기애', '거들먹'],
    keyword: 'ㄴㄱㅈㅂ',
    episodeNum: 339,
    episodeDate: '2013년 7월 20일',
    episodeName: '완전 남자다잉',
  },
  {
    title: '뺨이라도 후려치고 싶고',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-155.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-155.png?raw=true',
    cast: ['노홍철'],
    tags: ['분노', '화남', '호소'],
    keyword: 'ㅃㅇㄹㄷㅎㄹㅊㄱㅅㄱ',
    episodeNum: 173,
    episodeDate: '2009년10월 3일 ',
    episodeName: '무한도전 TV',
  },
  {
    title: '제영재… 앞으로 하나 뒤로 하나 똑같죠',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-156.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-156.png?raw=true',
    cast: ['박명수'],
    tags: ['진지함', '심문'],
    keyword: 'ㅈㅇㅈㅇㅍㄹㅎㄴㄷㄹㅎㄴㄸㄱㅈ',
    episodeNum: 194,
    episodeDate: '2010년 2월 27일',
    episodeName: '죄와 길',
  },
  {
    title: '아우 장난치지말고 빨리 자장면 주세요!!',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-157.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-157.png?raw=true',
    cast: ['정형돈'],
    tags: ['화남', '짜증', '진상', '폭발', '제발', '자장면'],
    keyword: 'ㅇㅇㅈㄴㅊㅈㅁㄱㅃㄹㅉㅈㅁㅈㅅㅇ',
    episodeNum: 150,
    episodeDate: '2009년 4월 18일',
    episodeName: 'YES or NO 인생각장 특집',
  },
  {
    title: '줄리어스 로버트 오펜하이머',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-158.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-158.png?raw=true',
    cast: ['하하'],
    tags: ['발표', '독후감'],
    keyword: 'ㅈㄹㅇㅅㄹㅂㅌㅇㅍㅎㅇㅁ',
    episodeNum: 240,
    episodeDate: '2011년 3월 12일',
    episodeName: '정총무 책책책 책을 읽읍시다',
  },
  {
    title: '사기꾼 말 한마디에 초토화된 세 가정',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-159.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-159.png?raw=true',
    cast: ['하하'],
    tags: ['다급', '전화', '사기꾼'],
    keyword: 'ㅅㄱㄲㅁㅎㅁㄷㅇㅊㅌㅎㄷㅅㄱㅈ',
    episodeNum: 333,
    episodeDate: '2013년 6월 8일',
    episodeName: '마이너리티 리포트',
  },
  {
    title: '꼴값들 떨고…',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-160.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-160.png?raw=true',
    cast: ['하하'],
    tags: ['짜증', '꼴값'],
    keyword: 'ㄲㄱㄷㄸㄱ',
    episodeNum: 346,
    episodeDate: '2014년 1월 11일',
    episodeName: 'IF 만약에',
  },
  {
    title: '형돈정 ',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-161.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-161.png?raw=true',
    cast: ['정형돈'],
    tags: ['영어', '평범'],
    keyword: 'ㅎㄷㅈ',
    episodeNum: 39,
    episodeDate: '2007년 2월 3일',
    episodeName: '어학연수 특집',
  },
  {
    title: '옥수수차?',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-162.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-162.png?raw=true',
    cast: ['유재석'],
    tags: ['황당', '괘씸', '옥수수차'],
    keyword: 'ㅇㅅㅅㅊ',
    episodeNum: 173,
    episodeDate: '2009년 10월 3일',
    episodeName: '무한도전 TV',
  },
  {
    title: '후렴은 나의 것!',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-163.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-163.png?raw=true',
    cast: ['유재석'],
    tags: ['진상', '노래', '후렴'],
    keyword: 'ㅎㄹㅇㄴㅇㄱ',
    episodeNum: 250,
    episodeDate: '2011년 5월 21일',
    episodeName: '무한상사 야유회',
  },
  {
    title: '동공얼음',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-164.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-164.png?raw=true',
    cast: ['하하'],
    tags: ['겁', '쫄음', '놀람'],
    keyword: 'ㄷㄱㅇㅇ',
    episodeNum: 465,
    episodeDate: '2016년 1월 30일',
    episodeName: '예능 학교 스쿨 오브 樂',
  },
  {
    title: '한 번은 참을게요 두 번은 안 돼요',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-165.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-165.png?raw=true',
    cast: ['노홍철'],
    tags: ['애교', '경고', '영상편지'],
    keyword: 'ㅎㅂㅇㅊㅇㄱㅇㄷㅂㅇㅇㄷㅇ',
    episodeNum: 219,
    episodeDate: '2010년 10월 9일',
    episodeName: '2011 도전! 달력모델',
  },
  {
    title: '아니! 아닌데!',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-166.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-166.png?raw=true',
    cast: ['정형돈'],
    tags: ['아니', '아닌데', '사춘기', '청개구리'],
    keyword: 'ㅇㄴㅇㄴㄷ',
    episodeNum: 323,
    episodeDate: '2013년 3월 30일',
    episodeName: '와이키키 브라더스',
  },
  {
    title: '밥 갖고 와!',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-167.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-167.png?raw=true',
    cast: ['노홍철'],
    tags: ['밥', '광기', '포효', '신경질'],
    keyword: 'ㅂㄱㄱㅇ',
    episodeNum: 174,
    episodeDate: '2009년 10월 10일',
    episodeName: '무한도전 TV',
  },
  {
    title: '아니! 끼역 띠귿 해야지',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-168.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-168.png?raw=true',
    cast: ['하하'],
    tags: ['맞춤법', '한글'],
    keyword: 'ㅇㄴㄲㅇㄸㄱㅎㅇㅈ',
    episodeNum: 231,
    episodeDate: '2011년 1월 8일',
    episodeName: '정총무가 쏜다',
  },
  {
    title: '니네 잘 못 노는구나!',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-169.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-169.png?raw=true',
    cast: ['하하'],
    tags: ['거들먹', '비웃음'],
    keyword: 'ㄴㄴㅈㅁㄴㄴㄱㄴ',
    episodeNum: 247,
    episodeDate: '2011년 4월 30일',
    episodeName: '무한도전 가요제 디너쇼',
  },
  {
    title: '3분 안에 풀 수 있어요',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-170.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-170.png?raw=true',
    cast: ['하하'],
    tags: ['수능', '학생', '시험'],
    keyword: '3ㅂㅇㅇㅍㅅㅇㅇㅇ',
    episodeNum: 548,
    episodeDate: '2017년 12월 9일',
    episodeName: '2018학년도 수학능력시험',
  },
  {
    title: '흐뭇',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-171.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-171.png?raw=true',
    cast: ['하하'],
    tags: ['미소', '웃음', '흐뭇'],
    keyword: 'ㅎㅁ',
    episodeNum: 302,
    episodeDate: '2012년 11월 3일',
    episodeName: '언니의 유혹',
  },
  {
    title: '전하 목이라도 칠깝쇼',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-172.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-172.png?raw=true',
    cast: ['하하'],
    tags: ['백정', '전하', '건의'],
    keyword: 'ㅈㅎㅁㅇㄹㄷㅊㄲㅅ',
    episodeNum: 355,
    episodeDate: '2013년 11월 9일',
    episodeName: '관상',
  },
  {
    title: '망해라!',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-173.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-173.png?raw=true',
    cast: ['하하'],
    tags: ['저주', '막말', '악담', '비난'],
    keyword: 'ㅁㅎㄹ',
    episodeNum: 393,
    episodeDate: '2014년 8월 23일',
    episodeName: '형광팬',
  },
  {
    title: '뭔소리야',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-174.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-174.png?raw=true',
    cast: ['하하'],
    tags: ['답답', '한심'],
    keyword: 'ㅁㅅㄹㅇ',
    episodeNum: 392,
    episodeDate: '2014년 8월 16일',
    episodeName: '도둑들',
  },
  {
    title: '난 완전 좋아!!',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-175.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-175.png?raw=true',
    cast: ['하하'],
    tags: ['콜', '좋아', '오케이'],
    keyword: 'ㄴㅇㅈㅈㅇ',
    episodeNum: 382,
    episodeDate: '2014년 6월 7일',
    episodeName: '배고픈 특집',
  },
  {
    title: '뭐… 어쩌라고',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-176.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-176.png?raw=true',
    cast: ['하하'],
    tags: ['답답', '무시', '어쩔'],
    keyword: 'ㅁㅇㅉㄹㄱ',
    episodeNum: 239,
    episodeDate: '2011년 3월 5일',
    episodeName: '사생결단',
  },
  {
    title: '그냥… 때릴까…?',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-177.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-177.png?raw=true',
    cast: ['하하'],
    tags: ['답답', '한심'],
    keyword: 'ㄱㄴㄸㄹㄲ',
    episodeNum: 322,
    episodeDate: '2013년 3월 23일',
    episodeName: '와이키키 브라더스',
  },
  {
    title: '잡고! 빵!!',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-178.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-178.png?raw=true',
    cast: ['하하'],
    tags: ['생일', '축하', '케이크', '빵'],
    keyword: 'ㅈㄱㅃ',
    episodeNum: 278,
    episodeDate: '2011년 12월 3일',
    episodeName: '명수는 12살',
  },
  {
    title: '꺄아',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-179.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-179.png?raw=true',
    cast: ['박명수'],
    tags: ['생일', '행복', '유쾌'],
    keyword: 'ㄲㅇ',
    episodeNum: 278,
    episodeDate: '2011년 12월 3일',
    episodeName: '명수는 12살',
  },
  {
    title: '생일 축하~~ 합니다~~',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-182.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-182.png?raw=true',
    cast: ['노홍철', '길'],
    tags: ['생일', '축하', '노래'],
    keyword: 'ㅅㅇㅊㅎㅎㄴㄷ',
    episodeNum: 278,
    episodeDate: '2011년 12월 3일',
    episodeName: '명수는 12살',
  },
  {
    title: '되게 당황스럽다 정말',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-181.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-181.png?raw=true',
    cast: ['하하'],
    tags: ['당황', '땀'],
    keyword: 'ㄷㄱㄷㅎㅅㄹㄷㅈㅁ',
    episodeNum: 340,
    episodeDate: '2013년 7월 27일',
    episodeName: '소문난 칠공주',
  },
  {
    title: '한판 붙자',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-180.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-180.png?raw=true',
    cast: ['하하'],
    tags: ['화남', '결투', '짜증'],
    keyword: 'ㅎㅍㅂㅈ',
    episodeNum: 291,
    episodeDate: '2012년 8월 11일',
    episodeName: '말하는대로',
  },
  {
    title: '얼굴 지존 소년 명수',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-183.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-183.png?raw=true',
    cast: ['박명수'],
    tags: ['웃음', '얼굴', '개인기'],
    keyword: 'ㅇㄱㅈㅈㅅㄴㅁㅅ',
    episodeNum: 64,
    episodeDate: '2007년 7월 28일',
    episodeName: '개그 실미도',
  },
  {
    title: '빨리 갖고 와',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-184.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-184.png?raw=true',
    cast: ['박명수'],
    tags: ['명령', '광기', '협박'],
    keyword: 'ㅃㄹㄱㄱㅇ',
    episodeNum: 294,
    episodeDate: '2012년 9월 8일',
    episodeName: '약속한대로',
  },
  {
    title: '월매댄스 원조 명수옹',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-185.png?raw=true',
    gameImgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudoGame-185.png?raw=true',
    cast: ['박명수'],
    tags: ['춤', '댄스'],
    keyword: 'ㅇㅁㄷㅅㅇㅈㅁㅅㅇ',
    episodeNum: 176,
    episodeDate: '2009년 10월 24일',
    episodeName: '벼농사 특집',
  },
];

const seed = async () => {
  try {
    const batch = writeBatch(db);
    const tagCounter = new Map<string, number>();

    console.log('Images 데이터와 태그 카운트 집계를 시작합니다...');

    for (const item of dummyData) {
      const newImageRef = doc(collection(db, 'Images'));
      batch.set(newImageRef, item);

      for (const tag of item.tags) {
        const currentCount = tagCounter.get(tag) || 0;
        tagCounter.set(tag, currentCount + 1);
      }
    }

    console.log(`총 ${dummyData.length}개의 Images 문서를 배치에 추가했습니다.`);

    for (const [tag, count] of tagCounter.entries()) {
      const tagDocRef = doc(db, 'tagCounts', tag);
      batch.set(tagDocRef, { count: count }); // 배치에 쓰기 작업 추가
    }

    console.log(`총 ${tagCounter.size}개의 tagCounts 문서를 배치에 추가했습니다.`);

    await batch.commit();

    console.log('Firestore에 모든 더미 데이터와 태그 카운트가 성공적으로 추가되었습니다!');
  } catch (error) {
    console.error('데이터 시딩 중 오류 발생:', error);
  }
};

seed();
