// scripts/seed.ts
import { initializeApp } from 'firebase/app';
import { getFirestore, collection, addDoc } from 'firebase/firestore';

const firebaseConfig = {
  apiKey: 'AIzaSyDWD_-8YS0ov4ufsb1qOCwn2xHJRQajlzk',
  authDomain: 'mudo-project-9666a.firebaseapp.com',
  projectId: 'mudo-project-9666a',
  storageBucket: 'mudo-project-9666a.firebasestorage.app',
  messagingSenderId: '953204120724',
  appId: '1:953204120724:web:439065152574d205946881',
  measurementId: 'G-2ZC9SXZ9NC',
};

// Firebase 초기화
const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

// 더미 데이터
const dummyData = [
  {
    title: '약간 모자라지만 착한 친구야',
    description: '멍청이를 우리말로 순화해서 말하는 장면',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-002.png?raw=true',
    cast: ['정준하'],
    tags: ['웃김', '놀림', '디스'],
    keyword: 'ㅇㄱㅁㅈㄹㅈㅁㅊㅎㅊㄱㅇ',
    episodeNum: 270,
    episodeDate: '2011년 10월 8일',
    episodeName: '무한상사 특집',
  },
  {
    title: '정신차려 이 각박한 세상속에서',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-003.png?raw=true',
    cast: ['하하'],
    tags: ['웃김', '경고', '설득', '자막짤'],
    keyword: 'ㅈㅅㅊㄹㅇㄱㅂㅎㅅㅅㅅㅇㅅ',
    episodeNum: 333,
    episodeDate: '2013년 6월 8일',
    episodeName: '행쇼',
  },
  {
    title: '지금 지쳤나요?',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-004.png?raw=true',
    cast: ['홍진경'],
    tags: ['웃김', '힘듦', '피곤', '자막짤'],
    keyword: 'ㅈㄱㅈㅊㄴㅇ?',
    episodeNum: 422,
    episodeDate: '2015년 4월 4일',
    episodeName: '식스맨 특집',
  },
  {
    title: '사랑아, 보영해',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-005.png?raw=true',
    cast: ['정형돈', '일반인'],
    tags: ['웃김', '사랑', '자막짤'],
    keyword: 'ㅅㄹㅇㅂㅇㅎ',
    episodeNum: 280,
    episodeDate: '2011년 12월 17일',
    episodeName: '무한택배',
  },
  {
    title: '형이 왜 거기서 나와?',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-006.png?raw=true',
    cast: ['정형돈'],
    tags: ['웃김', '왜 거기서 나와', '당황', '자막짤'],
    keyword: 'ㅎㅇㅇㄱㄱㅅㄴㅇ?',
    episodeNum: 408,
    episodeDate: '2014년 12월 13일',
    episodeName: '유혹의 거인',
  },
  {
    title: '출바알',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-007.png?raw=true',
    cast: ['박명수'],
    tags: ['출발', '여행', '자막짤'],
    keyword: 'ㅊㅂㅇ',
    episodeNum: 266,
    episodeDate: '2011년 9월 10일',
    episodeName: '한가위 선물 특집',
  },
  {
    title: '정자룡이 간다 간다 뿅 간다',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-008.png?raw=true',
    cast: ['박명수', '정준하', '길'],
    tags: ['웃김', '가자', '자막짤'],
    keyword: 'ㅈㅈㄹㅇㄱㄷㄱㄷㅃㄱㄷ',
    episodeNum: 217,
    episodeDate: '2010년 09월 25일',
    episodeName: '다 같이 돌자 서울 한바퀴~ 빙고 특집',
  },
  {
    title: '늦었다고 생각할 때가 진짜 너무 늦었다',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-009.png?raw=true',
    cast: ['박명수'],
    tags: ['충고', '늦음', '공부', '지각'],
    keyword: 'ㄴㅇㄷㄱㅅㄱㅎㄸㄱㅈㅉㄴㅁㄴㅇㄷ',
    episodeNum: 164,
    episodeDate: '2009년 8월 1일',
    episodeName: '소원을 말해봐 특집',
  },
  {
    title: '꿈은 없고요 그냥 놀고 싶습니다',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-010.png?raw=true',
    cast: ['무도멤버'],
    tags: ['지침', '공부', '놀자', '쉬자'],
    keyword: 'ㄲㅇㅇㄱㅇㄱㄴㄴㄱㅅㅅㄴㄷ',
    episodeNum: 343,
    episodeDate: '2013년 8월 17일',
    episodeName: '무도를 부탁해',
  },
  {
    title: '나 드러워서 못하겠네',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-011.png?raw=true',
    cast: ['박명수', '정준하'],
    tags: ['', '', ''],
    keyword: 'ㄴㄷㄹㅇㅅㅁㅎㄱㄴ',
    episodeNum: 410,
    episodeDate: '2014년 12월 27일',
    episodeName: '토토가',
  },
  {
    title: '말 좀 제대로 해라',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-012.png?raw=true',
    cast: ['하하', '정형돈'],
    tags: ['', '', ''],
    keyword: 'ㅁㅈㅈㄷㄹㅎㄹ',
    episodeNum: 292,
    episodeDate: '2012년 8월 25일',
    episodeName: '니가 가라 하와이',
  },
  {
    title: '일본 형돈이',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-013.png?raw=true',
    cast: ['정준하'],
    tags: ['', '', ''],
    keyword: 'ㅇㅂㅎㄷㅇ',
    episodeNum: 237,
    episodeDate: '2011년 2월 19일',
    episodeName: '오호츠크해 특집',
  },
  {
    title: '유식해 보이는 무식한 답변',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-014.png?raw=true',
    cast: ['하하'],
    tags: ['', '', ''],
    keyword: 'ㅇㅅㅎㅂㅇㄴㅁㅅㅎㄷㅂ',
    episodeNum: 238,
    episodeDate: '2011년 2월 26일',
    episodeName: '오호츠크해 특집',
  },
  {
    title: '아버지 나를 낳으시고 바지적삼 다적시셨네',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-015.png?raw=true',
    cast: ['정준하', '박명수', '유재석'],
    tags: ['', '', ''],
    keyword: 'ㅇㅂㅈㄴㄹㄴㅇㅅㄱㅂㅈㅈㅅㄷㅈㅅㅅㄴ',
    episodeNum: 298,
    episodeDate: '2012년 10월 6일',
    episodeName: '추석특집 무한상사',
  },
  {
    title: '뱀이야 xx야',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-016.png?raw=true',
    cast: ['길', '정형돈'],
    tags: ['', '', ''],
    keyword: 'ㅂㅇㅇXXㅇ',
    episodeNum: 344,
    episodeDate: '2013년 8월 24일',
    episodeName: '무도를 부탁해',
  },
  {
    title: '점 오',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-017.png?raw=true',
    cast: ['박명수'],
    tags: ['', '', ''],
    keyword: 'ㅈㅇ',
    episodeNum: 194,
    episodeDate: '2010년 2월 27일',
    episodeName: '죄와 길',
  },
  {
    title: '한머리 두냄새',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-018.png?raw=true',
    cast: ['유재석', '정형돈', '박명수', '하하', '정준하', '길'],
    tags: ['', '', ''],
    keyword: 'ㅎㅁㄹㄷㄴㅅ',
    episodeNum: 204,
    episodeDate: '2010년 6월 26일',
    episodeName: '자리분양 특집',
  },
  {
    title: '간염에 걸렸을때 일어나지 못했더라면',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-019.png?raw=true',
    cast: ['박명수'],
    tags: ['', '', ''],
    keyword: 'ㄱㅇㅇㄱㄹㅇㄸㅇㅇㄴㅈㅁㅎㄷㄹㅁ',
    episodeNum: 363,
    episodeDate: '2014년 1월 4일',
    episodeName: 'IF 만약에',
  },
  {
    title: '이제는 더 이상 물러날 곳이 없다',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-020.png?raw=true',
    cast: ['정준하'],
    tags: ['', '', ''],
    keyword: 'ㅇㅈㄴㄷㅇㅅㅁㄹㄴㄱㅇㅇㄷ',
    episodeNum: 274,
    episodeDate: '2011년 11월 5일',
    episodeName: '수학능력평가 특집',
  },
  {
    title: '형보다 잘할걸?',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-021.png?raw=true',
    cast: ['길'],
    tags: ['', '', ''],
    keyword: 'ㅎㅂㄷㅈㅎㄱ?',
    episodeNum: 292,
    episodeDate: '2012년 8월 25일',
    episodeName: '무한뉴스',
  },
  {
    title: '아유... 하기 싫어...',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-022.png?raw=true',
    cast: ['박명수'],
    tags: ['', '', ''],
    keyword: 'ㅇㅇㅎㄱㅅㅇ',
    episodeNum: 285,
    episodeDate: '2012년 1월 21일',
    episodeName: '무한상사',
  },
  {
    title: '참재밌다',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-023.png?raw=true',
    cast: ['박명수'],
    tags: ['', '', ''],
    keyword: 'ㅊㅈㅁㄷ',
    episodeNum: 278,
    episodeDate: '2011년 12월 3일',
    episodeName: '명수는 12살',
  },
  {
    title: '자 이게 클릭이야',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-024.png?raw=true',
    cast: ['노홍철', '하하'],
    tags: ['', '', ''],
    keyword: 'ㅈㅇㄱㅋㄹㅇㅇ',
    episodeNum: 270,
    episodeDate: '2011년 10월 8일',
    episodeName: '무한상사',
  },
  {
    title: '형이 모자라다고 말 함부로 하냐',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-025.png?raw=true',
    cast: ['박명수'],
    tags: ['', '', ''],
    keyword: 'ㅎㅇㅁㅈㄹㄷㄱㅁㅎㅂㄹㅎㄴ',
    episodeNum: 38,
    episodeDate: '2007년 1월 27일',
    episodeName: '7080 복고 특집',
  },
  {
    title: '그래도 하시겠습니까?',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-026.png?raw=true',
    cast: ['일반인'],
    tags: ['', '', ''],
    keyword: 'ㄱㄹㄷㅎㅅㄱㅅㄴㄲ',
    episodeNum: 194,
    episodeDate: '2010년 2월 27일',
    episodeName: '죄와 길',
  },
  {
    title: '반갑다 x세대 여러분',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-027.png?raw=true',
    cast: ['박명수'],
    tags: ['', '', ''],
    keyword: 'ㅂㄱㄷxㅅㄷㅇㄹㅂ',
    episodeNum: 289,
    episodeDate: '2012년 8월 4일',
    episodeName: '개그학개론',
  },
  {
    title: '무야호',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-028.png?raw=true',
    cast: ['일반인'],
    tags: ['', '', ''],
    keyword: 'ㅁㅇㅎ',
    episodeNum: 195,
    episodeDate: '2010년 3월 6일',
    episodeName: '오 마이 텐트 특집',
  },
  {
    title: '더덩실 더덩실',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-029.png?raw=true',
    cast: ['유재석', '박명수'],
    tags: ['', '', ''],
    keyword: 'ㄷㄷㅅㄷㄷㅅ',
    episodeNum: 175,
    episodeDate: '2009년 10월 17일',
    episodeName: '벼농사 특집',
  },
  {
    title: '지난번만 못하네요 어머님',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-030.png?raw=true',
    cast: ['박명수'],
    tags: ['', '', ''],
    keyword: 'ㅈㄴㅂㅁㅁㅎㄴㅇㅇㅁㄴ',
    episodeNum: 132,
    episodeDate: '2008년 11월 29일',
    episodeName: '무한도전, 에어로빅에 도전하다',
  },
  {
    title: '법보다 가까운 주먹',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-031.png?raw=true',
    cast: ['박명수', '유재석', '정준하', '정형돈'],
    tags: ['', '', ''],
    keyword: 'ㅂㅂㄷㄱㄲㅇㅈㅁ',
    episodeNum: 193,
    episodeDate: '2010년 2월 20일',
    episodeName: '죄와 길',
  },
  {
    title: '친구들아 고맙다',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-032.png?raw=true',
    cast: ['박명수'],
    tags: ['', '', ''],
    keyword: 'ㅊㄱㄷㅇㄱㅁㄷ',
    episodeNum: 278,
    episodeDate: '2011년 12월 3일',
    episodeName: '명수는 12살',
  },
  {
    title: '한번 고소당해야 정신 차리시겠습니까',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-033.png?raw=true',
    cast: ['박명수'],
    tags: ['', '', ''],
    keyword: 'ㅎㅂㄱㅅㄷㅎㅇㅈㅅㅊㄹㅅㄱㅅㄴㄲ',
    episodeNum: 279,
    episodeDate: '2011년 12월 10일',
    episodeName: '명수는 12살',
  },
  {
    title: '홍철이 없는 홍철팀 탄생',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-034.png?raw=true',
    cast: ['길', '유재석', '정준하', '하하', '박명수'],
    tags: ['', '', ''],
    keyword: 'ㅎㅊㅇㅇㄴㅎㅊㅌㅌㅅ',
    episodeNum: 217,
    episodeDate: '2010년 9월 25일',
    episodeName: '다 같이 돌자 서울 한바퀴~ 빙고 특집',
  },
  {
    title: '족발 당수 워어어어',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-035.png?raw=true',
    cast: ['정형돈'],
    tags: ['', '', ''],
    keyword: 'ㅈㅂㄷㅅㅇㅇㅇㅇ',
    episodeNum: 163,
    episodeDate: '2009년 7월 25일',
    episodeName: 'SOS 해양구조대 특집',
  },
  {
    title: '쯔왑 쯔왑',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-036.png?raw=true',
    cast: ['황광희'],
    tags: ['', '', ''],
    keyword: 'ㅉㅇㅉㅇ',
    episodeNum: 461,
    episodeDate: '2016년 1월 2일',
    episodeName: '무도 공개수배',
  },
  {
    title: '너 왜 반말?',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-037.png?raw=true',
    cast: ['유병재'],
    tags: ['', '', ''],
    keyword: 'ㄴㅇㅂㅁ?',
    episodeNum: 421,
    episodeDate: '2015년 3월 28일',
    episodeName: '식스맨',
  },
  {
    title: '참... 좋다',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-038.png?raw=true',
    cast: ['정준하'],
    tags: ['', '', ''],
    keyword: 'ㅊ...ㅈㄷ',
    episodeNum: 281,
    episodeDate: '2011년 12월 24일',
    episodeName: '무한택배',
  },
  {
    title: '성희롱 당한 NO홍철',
    description: '',
    imgPath: 'https://github.com/jaehyun0620/mudo-images/blob/main/images/mudo-039.png?raw=true',
    cast: ['노홍철'],
    tags: ['', '', ''],
    keyword: 'ㅅㅎㄹㄷㅎNOㅎㅊ',
    episodeNum: 274,
    episodeDate: '2011년 11월 5일',
    episodeName: '수학능력평가 특집',
  },
];

const seed = async () => {
  for (const item of dummyData) {
    await addDoc(collection(db, 'Images'), item);
  }
  console.log(' Firestore에 더미 데이터가 추가되었습니다.');
};

seed();
